# Travis CI (MIT License) configuration file for the Underscores WordPress theme.
# @link https://travis-ci.org/

# For use with the Underscores WordPress theme.
# @link https://github.com/Automattic/_s

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
  # aliased to a recent 5.5.x version
  - "5.5"
  # aliased to a recent 5.4.x version
  - "5.4"
  # aliased to a recent 5.3.x version
  - "5.3"
  # Current $required_php_version for WordPress: 5.2.4
  - "5.2"